config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  default_url_options host: 'localhost:3000'
  root 'duties#index'

  resources :users
  resources :duties, only: [:index] do
    collection do
      patch '/grab', to: 'duties#process_grab'
      patch '/drop', to: 'duties#process_drop'
      get '/mass-edit', to: 'duties#mass_edit'
      patch '/mass-update', to: 'duties#mass_update'
    end
  end
  resources :places
  resources :timeslots

  get '/admin', to: 'others#admin'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NUSSU commIT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="widspan=device-widspan, initial-scale=1">
  </head>

  <% if (yield :no_nav).empty? %>
    <body>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#app-navbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'NUSSU commIT', root_path, class: 'navbar-brand' %>
          </div>
          <div class="collapse navbar-collapse" id="app-navbar">
            <ul class="nav navbar-nav">
              <li><a href="#">Grab Duty</a></li>
              <li><a href="#">Problem Report</a></li>
              <li><a href="#">Timesheet</a></li>
              <li><%= link_to 'Members', users_path %></li>
              <li><a href="#">Guide</a></li>
              <li><a href="#">EOD</a></li>
              <li><%= link_to 'Admin', admin_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="glyphicon glyphicon-user"></span>
                  <%= current_user.username %>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#">My Profile</a></li>
                  <li><a href="#">Schedule Availability</a></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>

    <%= console if params[:c] %>

    <div class="container">
      <p class="flash-notice"><%= notice %></p>
      <p class="flash-alert"><%= alert %></p>
      <%= yield %>
    </div>
    </body>
</html>